import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
import re
from dotenv import load_dotenv

load_dotenv()

def make_links_clickable(text):
    url_pattern = r'(https?://[^\s<>]+)'
    return re.sub(url_pattern, r'<a href="\1" style="color:#0066cc; text-decoration:underline;">\1</a>', text)

def format_report_html(report: str) -> str:
    # Convert markdown bold **text** to HTML bold
    report = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', report)
    
    # Make URLs clickable
    report = make_links_clickable(report)
    
    # Convert newlines to <br>
    report = report.replace('\n', '<br>')
    
    # Make emoji headings stand out
    report = report.replace('📰', '<br><span style="font-size:20px;">📰</span>')
    report = report.replace('🧠', '<br><span style="font-size:20px;">🧠</span>')
    report = report.replace('📚', '<br><span style="font-size:20px;">📚</span>')
    report = report.replace('📅', '<br><span style="font-size:20px;">📅</span>')
    report = report.replace('🔗', '<br><span style="font-size:20px;">🔗</span>')
    
    return report

def send_email(report: str):
    sender = os.getenv("GMAIL_ADDRESS")
    password = os.getenv("GMAIL_APP_PASSWORD")
    receiver = os.getenv("GMAIL_ADDRESS")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "🤖 Your Daily AI Learning Report"
    msg["From"] = sender
    msg["To"] = receiver

    # Plain text version
    text_part = MIMEText(report, "plain")

    # Format report for HTML
    formatted_report = format_report_html(report)

    # HTML version
    html_content = f"""
    <html>
    <body style="font-family: 'Georgia', serif; max-width: 650px; 
                 margin: auto; padding: 40px 20px; background-color: #f4f1ea; color: #333333;">
        <div style="background-color: #ffffff; padding: 40px; 
                    border: 1px solid #dcd2c6; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
            
            <!-- Header -->
            <div style="text-align: center; border-bottom: 2px solid #333333; 
                        padding-bottom: 20px; margin-bottom: 30px;">
                <h1 style="margin: 0; font-size: 28px; font-weight: normal; 
                            color: #1a1a1a; letter-spacing: 1px;">
                    Daily AI Learning Report
                </h1>
                <p style="margin: 10px 0 0 0; font-style: italic; 
                           color: #666666; font-size: 14px;">
                    Curated Insights & Updates
                </p>
            </div>

            <!-- Report Content -->
            <div style="line-height: 1.9; font-size: 15px; color: #2c2c2c;">
                {formatted_report}
            </div>

            <!-- Footer -->
            <div style="text-align: center; margin-top: 40px; padding-top: 20px; 
                        border-top: 1px solid #eeeeee; color: #888888; 
                        font-size: 12px; font-style: italic;">
                Generated by NeuraFlow 🤖 | Your Personal AI Learning Intelligence System
            </div>
        </div>
    </body>
    </html>
    """

    html_part = MIMEText(html_content, "html")
    msg.attach(text_part)
    msg.attach(html_part)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, receiver, msg.as_string())
        print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Email failed: {e}")

if __name__ == "__main__":
    test_report = "🧪 Test email!\n\n🔗 **MUST-READ LINKS**\n- Check this: https://arxiv.org\n- And this: https://huggingface.co"
    send_email(test_report)